name: Compie CI/CD

on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::367425865577:role/GitHubActionsECRPushRole
          aws-region: us-east-1
          retry-max-attempts: 1  # Stop loop and print actual error immediately

      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/daniel_dev/compie_app:${{ github.sha }} -t ${{ steps.login-ecr.outputs.registry }}/daniel_dev/compie_app:latest .

      - name: Run Pytest inside Container
        run: |
          # 1. Fetch exact parameters using your environment prefix
          AWS_REGION=$(aws ssm get-parameter --name "/production/compie_app/AWS_REGION" --query "Parameter.Value" --output text)
          DYNAMODB_TABLE=$(aws ssm get-parameter --name "/production/compie_app/DYNAMODB_TABLE" --query "Parameter.Value" --output text)

          # 2. Pass fetched parameters into the container run step
          # ('python -m pytest' automatically adds /app to sys.path)
          docker run --rm \
            -e AWS_REGION="$AWS_REGION" \
            -e DYNAMODB_TABLE="$DYNAMODB_TABLE" \
            ${{ steps.login-ecr.outputs.registry }}/daniel_dev/compie_app:${{ github.sha }} python -m pytest -v

      - name: Push to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/daniel_dev/compie_app:${{ github.sha }}
          docker push ${{ steps.login-ecr.outputs.registry }}/daniel_dev/compie_app:latest

      - name: Deploy (Trigger ASG Instance Refresh)
        run: |
          aws autoscaling start-instance-refresh \
            --auto-scaling-group-name "production-asg-20260730181127912900000008" \
            --preferences '{"MinHealthyPercentage": 50}'